# Generated by Django 2.0.5 on 2018-09-14 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='E-mail účastníka')),
                ('gdpr', models.BooleanField(help_text='Souhlasím se zpracováním poskytnutých osobních údajů\n            a zařazením do databáze uživatelů společnosti OpenGeoLabs s.r.o.\n            se sídlem v Brandlova 1559/7, Praha 11, 149 00 (dále jen\n            OpenGeoLabs s.r.o.) pro vlastní použití v souladu s příslušnými\n            ustanoveními zákona č. 101 / 2000 Sb. O ochraně osobních údajů a o\n            změně některých údajů v platném znění. Beru na vědomí, že údaje\n            budou využívány pouze v rámci společnosti OpenGeoLabs s.r.o.. Jsem\n            si vědom/a toho, že souhlas s jejich zpracováním mohu kdykoliv\n            odvolat zasláním e-mailu na adresu info [zavináč] opengeolabs\n            [tečka] cz. Souhlas bude automaticky prodloužen vždy o další roční\n            období, pokud nedojde k jeho odvolání písemnou formou. Jsem si\n            vědom/a svých práv, které subjektům poskytuje zákon 101/2000 Sb., o\n            ochraně osobních údajů. Vaše data budou použita pro potřeby\n            organizace školení GISMentors.\n            ', verbose_name='Souhlas se zpracováním osobních údajů')),
                ('marketing', models.BooleanField(help_text='Souhlasím s tím, že společnost OpenGeoLabs s.r.o.\n            může využít můj e-mail pro zaslání krátké marketingové zprávy (ne\n            častěji, než čtyřikrát za rok), obsahující informace o slevách a\n            mimořádných nabídkách a informace o aktuálním dění ve společnosti.\n            Jsem si vědom/a toho, že souhlas použití mého e-mailu\n            pro marketingové účely mohu kdykoliv odvolat zasláním\n            e-mailu na adresu info [zavináč] opengeolabs [tečka]\n            cz. Souhlas bude automaticky prodloužen vždy o další\n            roční období, pokud nedojde k jeho odvolání písemnou\n            formou. Jsem si vědom/a svých práv, které subjektům\n            poskytuje zákon 101/2000 Sb., o ochraně osobních údajů.\n            Na základě tohoto souhlasu budeme zpracovávat vaše\n            kontaktní údaje, údaje o absolvovaných kurzech u nás.\n            ', verbose_name='Souhlas s posíláním marketingových materiálů')),
                ('date_signed', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Učastník',
                'verbose_name_plural': 'Učastníci',
            },
        ),
        migrations.CreateModel(
            name='CourseAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='Datum přihlášení')),
                ('student', models.BooleanField(verbose_name='Student')),
                ('level', models.IntegerField(choices=[(0, 'Začátečník'), (1, 'Mírně pokročilý'), (2, 'Běžně pracuji s nástroji GIS'), (3, 'GIS profesionál')], verbose_name='Úroveň')),
                ('note', models.TextField(verbose_name='Poznámka')),
                ('topics', models.TextField(blank=True, verbose_name='Témata kurzu')),
                ('next_topics', models.TextField(blank=True, verbose_name='Témata dalších kurzu')),
                ('certificate', models.FileField(blank=True, upload_to='', verbose_name='Certifikát')),
                ('token', models.CharField(default=uuid.UUID('d14c947a-e447-455c-9888-a7bdc79f592b'), max_length=255, verbose_name='Token')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Attendee')),
            ],
            options={
                'verbose_name': 'Učastník kurzu',
                'verbose_name_plural': 'Učastníci kurzu',
            },
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Vytvořený'), ('published', 'Publikovaný'), ('closed', 'Uzavřený'), ('declined', 'Zrušený')], default='created', help_text='<dl>\n                    <dt>Vytvořený</dt>\n                    <dd>Kurz je vytvořený, ale v nabídce se ještě neukazuje</dd>\n                    <dt>Publikovaný</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů</dd>\n                    <dt>Uzavřený</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů, ale jako\n                    uzavřený pro přihlášky.</dd>\n                    <dt>Zrušený</dt>\n                    <dd>Kurz se ukazuje v naší nabídce kurzů, ale označený jako\n                    zrušený.</dd>\n                    </dl>\n                                ', max_length=10)),
                ('date', models.DateField(verbose_name='Datum')),
                ('early_date', models.DateField(verbose_name='Včasná registrace')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka ke kurzu')),
                ('price_regular', models.IntegerField(help_text='Kč, bez DPH <br/>\n        <dl>\n        <dt>Začátečník</dt><dd> 4000</dd>\n        <dt>Pokročilý</dt><dd> 6000</dd>\n        </dl>', verbose_name='Včasná registrace')),
                ('price_late', models.IntegerField(help_text='Kč, bez DPH<br />\n        <dl>\n        <dt>Začátečník</dt><dd>6000</dd>\n        <dt>Pokročilý</dt><dd>7000</dd>\n        </dl>\n        ', verbose_name='Standardní')),
                ('price_student', models.IntegerField(default=1000, help_text='Kč, bez DPH', verbose_name='Studentská')),
            ],
            options={
                'verbose_name': 'Školení',
                'verbose_name_plural': 'Školení',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název')),
                ('image', models.ImageField(upload_to='', verbose_name='Logo')),
                ('level', models.IntegerField(choices=[(0, 'Začátečník'), (1, 'Pokročilý')], verbose_name='Úroveň')),
                ('description', models.TextField(verbose_name='Popis')),
                ('materials', models.URLField(verbose_name='Materiály')),
                ('detail', models.URLField(verbose_name='Detailní link')),
                ('schedule', models.URLField(verbose_name='Rozvrh')),
            ],
            options={
                'verbose_name': 'Typ školení',
                'verbose_name_plural': 'Typ školení',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Fakturační adresa')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Název organizace')),
                ('ico', models.CharField(blank=True, max_length=12, null=True, verbose_name='IČ')),
                ('dic', models.CharField(blank=True, max_length=16, null=True, verbose_name='DIČ')),
                ('objednavka', models.CharField(blank=True, max_length=16, null=True, verbose_name='Číslo objednávky')),
                ('email', models.EmailField(max_length=254, verbose_name='Kontaktní e-mail')),
                ('amount', models.EmailField(help_text='Částka bez DPH', max_length=254, verbose_name='Částka')),
                ('invoice', models.FileField(blank=True, upload_to='', verbose_name='Faktura')),
                ('text', models.TextField(verbose_name='Obsah')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Souřadnice')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Místo konání',
                'verbose_name_plural': 'Místa konání',
            },
        ),
        migrations.AddField(
            model_name='courseevent',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.CourseType'),
        ),
        migrations.AddField(
            model_name='courseevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Location', verbose_name='Místo konání'),
        ),
        migrations.AddField(
            model_name='courseattendee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.CourseEvent'),
        ),
        migrations.AddField(
            model_name='courseattendee',
            name='invoice_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.InvoiceDetail'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='courses',
            field=models.ManyToManyField(blank=True, to='registration.CourseEvent'),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Location'),
        ),
    ]
