# Generated by Django 2.0.5 on 2018-08-30 14:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Fakturační adresa')),
                ('org', models.CharField(blank=True, max_length=64, null=True, verbose_name='Název organizace')),
                ('ico', models.CharField(blank=True, max_length=12, null=True, verbose_name='IČ')),
                ('dic', models.CharField(blank=True, max_length=16, null=True, verbose_name='DIČ')),
                ('objednavka', models.CharField(blank=True, max_length=16, null=True, verbose_name='Číslo objednávky')),
                ('email', models.EmailField(max_length=254, verbose_name='Kontaktní e-mail')),
            ],
            options={
                'verbose_name': 'Fakturační údaje',
                'verbose_name_plural': 'Fakturační údaje',
            },
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='course_attendee',
        ),
        migrations.AddField(
            model_name='courseattendee',
            name='date_signed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum přihlášení'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseevent',
            name='status',
            field=models.CharField(choices=[('created', 'Vytvořený'), ('published', 'Publikovaný'), ('closed', 'Uzavřený'), ('declined', 'Zrušený')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='token',
            field=models.TextField(default=uuid.UUID('ed6df25e-201d-46b1-8df9-08519efb7832'), verbose_name='Token'),
        ),
        migrations.DeleteModel(
            name='InvoiceDetails',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='course_attendees',
            field=models.ManyToManyField(to='registration.CourseAttendee'),
        ),
    ]
