# Generated by Django 2.0.5 on 2018-08-30 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180830_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseattendee',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.FileField(blank=True, upload_to='', verbose_name='Faktura'),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='token',
            field=models.TextField(default=uuid.UUID('3bd8c4af-e1ac-4788-b39c-ff2d64b48aae'), verbose_name='Token'),
        ),
    ]
