# Generated by Django 2.0.5 on 2018-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_invoice_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattendee',
            name='attended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
