# Generated by Django 2.0.5 on 2018-08-30 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180830_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='course_attendees',
        ),
        migrations.AddField(
            model_name='courseattendee',
            name='invoice_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registration.InvoiceDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='token',
            field=models.TextField(default=uuid.UUID('4bd7b84e-8139-42ba-b6ca-31ef44e76490'), verbose_name='Token'),
        ),
    ]
