# Generated by Django 2.0.5 on 2019-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_attendee_attended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Lector name')),
            ],
            options={
                'verbose_name': 'Školitel',
                'verbose_name_plural': 'Školitelé',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveField(
            model_name='courseattendee',
            name='certificate',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='certificate_content',
            field=models.TextField(default='', help_text='Každá položka na nový řádek', verbose_name='Obsah certifikátu'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='organisation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='price_late',
            field=models.IntegerField(help_text='Kč, bez DPH<br />\n        <dl>\n        <dt>Začátečník</dt><dd>5000</dd>\n        <dt>Pokročilý</dt><dd>7000</dd>\n        </dl>\n        ', verbose_name='Standardní'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='courseevent',
            name='lectors',
            field=models.ManyToManyField(to='registration.Lector'),
        ),
    ]
