# Generated by Django 2.1.4 on 2019-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_attendee_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendee',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
