# Generated by Django 2.1.4 on 2019-01-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190103_0905'),
        ('registration', '0005_certificates'),
    ]

    operations = [
    ]
