# Generated by Django 2.0.5 on 2019-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='objednavka',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='amount',
        ),
        migrations.AddField(
            model_name='courseattendee',
            name='amount',
            field=models.IntegerField(default=0, help_text='Částka bez DPH', verbose_name='Částka'),
            preserve_default=False,
        ),
    ]
