# Generated by Django 2.0.5 on 2019-01-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_invoices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Místo konání', 'verbose_name_plural': 'Místa konání'},
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='text',
        ),
    ]
