# Generated by Django 2.0.5 on 2019-01-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_faktury'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='note',
            field=models.TextField(blank=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='courseattendee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.CourseEvent', verbose_name='Kurz'),
        ),
    ]
