# Generated by Django 2.0.5 on 2019-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_faktury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevent',
            name='early_date',
            field=models.DateField(blank=True, verbose_name='Včasná registrace'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='status',
            field=models.CharField(choices=[('created', 'Vytvořený'), ('published', 'Publikovaný'), ('closed', 'Uzavřený'), ('declined', 'Zrušený'), ('past', 'Uplynulý')], default='created', help_text='<dl>\n                    <dt>Vytvořený</dt>\n                    <dd>Kurz je vytvořený, ale v nabídce se ještě neukazuje</dd>\n                    <dt>Publikovaný</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů</dd>\n                    <dt>Uzavřený</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů, ale jako\n                    uzavřený pro přihlášky.</dd>\n                    <dt>Zrušený</dt>\n                    <dd>Kurz se ukazuje v naší nabídce kurzů, ale označený jako\n                    zrušený.</dd>\n                    <dt>Uplynulý</dt>\n                    <dd>Kurz již proběhl - neukazuje se v naší veřejné nabídce kurzů.</dd>\n                    </dl>\n                                ', max_length=10),
        ),
    ]
