# Generated by Django 2.0.5 on 2019-04-12 13:11

from django.db import migrations, models
from django.conf import settings
import registration.models
from registration.models import InvoiceDetail, CourseType
import uuid
import os
import shutil


def move_files(apps, schema_editor):
    for invoice in InvoiceDetail.objects.exclude(invoice=''):
        file_name = invoice.invoice.name
        orig = os.path.join(settings.MEDIA_ROOT, file_name)
        new = invoice.invoice_path(file_name)
        shutil.move(orig, os.path.join(settings.MEDIA_ROOT, new))

        invoice.invoice = new
        invoice.uuid = uuid.uuid4()
        invoice.save()

    for ctype in CourseType.objects.exclude(image=''):
        file_name = ctype.image.name
        orig = os.path.join(settings.MEDIA_ROOT, file_name)
        new = ctype.logo_path(file_name)
        shutil.move(orig, os.path.join(settings.MEDIA_ROOT, new))

        ctype.image = new
        ctype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_faktury'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='uuid',
            field=models.TextField(blank=True, default="", verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='status',
            field=models.CharField(choices=[('created', 'Vytvořený'), ('published', 'Publikovaný'), ('closed', 'Uzavřený'), ('declined', 'Zrušený'), ('past', 'Uplynulý')], default='created', help_text='<dl>\n                    <dt>Vytvořený</dt>\n                    <dd>Kurz je vytvořený, ale v nabídce se ještě neukazuje</dd>\n                    <dt>Publikovaný</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů</dd>\n                    <dt>Uzavřený</dt>\n                    <dd>Kurz se ukazuje v naší veřejné nabídce kurzů, ale jako\n                    uzavřený pro přihlášky.</dd>\n                    <dt>Zrušený</dt>\n                    <dd>Kurz se ukazuje v naší nabídce kurzů, ale označený jako\n                    zrušený.</dd>\n                    <dt>Uplynulý</dt>\n                    <dd>Kurz již proběhl - neukazuje se v naší veřejné nabídce kurzů.</dd>\n                    </dl>\n                                ', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='image',
            field=models.ImageField(max_length=256, upload_to=registration.models.call_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice',
            field=models.FileField(max_length=256, blank=True, upload_to=registration.models.call_invoice_path, verbose_name='Faktura'),
        ),

        migrations.RunPython(move_files),
    ]
