# Generated by Django 2.1.5 on 2019-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_automatic_earlydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevent',
            name='price_late',
            field=models.IntegerField(help_text='Kč, s DPH<br/>\n        <dl>\n        <dt>Začátečník</dt><dd>6000</dd>\n        <dt>Pokročilý</dt><dd>8500</dd>\n        </dl>\n        ', verbose_name='Standardní'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='price_regular',
            field=models.IntegerField(help_text='Kč, s DPH <br/>\n        <dl>\n        <dt>Začátečník</dt><dd> 5000</dd>\n        <dt>Pokročilý</dt><dd> 7500</dd>\n        </dl>', verbose_name='Včasná registrace'),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='price_student',
            field=models.IntegerField(default=1500, help_text='Kč, s DPH', verbose_name='Studentská'),
        ),
    ]
