# Generated by Django 2.0.5 on 2019-09-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_mediaroot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendee',
            name='amount',
            field=models.IntegerField(verbose_name='Částka (s DPH)'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'Začátečník'), (1, 'Pokročilý')], verbose_name='Úroveň'),
        ),
    ]
