# Generated by Django 2.0.5 on 2019-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_level_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'Začátečník'), (1, 'Pokročilý')], null=True, verbose_name='Úroveň'),
        ),
    ]
